[package]
name = "sam"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sam-service = { path = "../../crates/sam-service" }
sam-protocol = { path = "../../crates/sam-protocol" }
sam-transport = { path = "../../crates/sam-transport" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
